services:
  backend:
    build:
      context: ./backend
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./backend/model:/app/model:ro

  web:
    build:
      context: ./web
    platform: linux/amd64
    environment:
      - MODEL_API_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
